version: "3"
services:
  mengliEureka:
    image: ${imageRepository}.${eurekaServiceName}:${TAG}
    container_name: mengliEureka
    hostname: mengliEureka
    build:
      context: ./${eurekaServiceName}
      dockerfile: Dockerfile
      args:
        SERVICE: ${eurekaServiceName}
        TAG: ${TAG}
    ports:
      - "11001:11001"
    restart: on-failure
    environment:
      - spring.profiles.active=docker
  mengliProducer:
    image: ${imageRepository}.${producerServiceName}:${TAG}
    container_name: mengliProducer
    hostname: mengliProducer
    build:
      context: ./${producerServiceName}
      dockerfile: Dockerfile
      args:
        SERVICE: ${producerServiceName}
        TAG: ${TAG}
    ports:
      - "11003:11003"
    depends_on:
      - mengliEureka
    restart: always
    volumes:
      - "./shells/wait-for-it.sh:/wait-for-it.sh"
    command: ./wait-for-it.sh mengliEureka:11001 -t 30 -- java -jar -Dspring.profiles.active=docker /app.jar
  mengliConsumer:
    image: ${imageRepository}.${consumerServiceName}:${TAG}
    container_name: mengliConsumer
    hostname: mengliConsumer
    build:
      context: ./${consumerServiceName}
      dockerfile: Dockerfile
      args:
        SERVICE: ${consumerServiceName}
        TAG: ${TAG}
    ports:
      - "11004:11004"
    depends_on:
      - mengliEureka
      - mengliProducer
    restart: always
    volumes:
      - "./shells/wait-for-it.sh:/wait-for-it.sh"
    command: ./wait-for-it.sh mengliProducer:11003 -t 45 -- java -jar -Dspring.profiles.active=docker /app.jar
  mengliGateway:
    image: ${imageRepository}.${gatewayServiceName}:${TAG}
    container_name: mengliGateway
    hostname: mengliGateway
    build:
      context: ./${gatewayServiceName}
      dockerfile: Dockerfile
      args:
        SERVICE: ${gatewayServiceName}
        TAG: ${TAG}
    ports:
      - "11002:11002"
    depends_on:
      - mengliEureka
      - mengliProducer
      - mengliConsumer
    restart: always
    volumes:
      - "./shells/wait-for-it.sh:/wait-for-it.sh"
    command: ./wait-for-it.sh mengliConsumer:11004 -t 60 -- java -jar -Dspring.profiles.active=docker /app.jar