version: "3"
services:
  paizEureka:
    image: pazieureka:v1
    hostname: paizEureka
    ports:
    - "11001:11001"
    # environment: 可以使用这个参数修改变量
    #  - spring.profiles.active=dev
  paziGateway:
    image: pazigateway:v1
    hostname: paziGateway
    ports:
      - "11002:11002"
    depends_on:
      - paizEureka
    volumes:
      - "./entrypoint.sh:/entrypoint.sh"
    environment:
      SLEEP_SECOND: 4
    tty: true
    entrypoint: /entrypoint.sh -d paizEureka:11001 -c 'java -jar /app.jar';
  paziProducer:
    image: paziproducer:v1
    hostname: paziProducer
    ports:
    - "11003:11003"
    depends_on:
      - paizEureka
      - paziGateway
    volumes:
      - "./entrypoint.sh:/entrypoint.sh"
    environment:
      SLEEP_SECOND: 4
    tty: true
    entrypoint: /entrypoint.sh -d paziGateway:11002 -c 'java -jar /app.jar';
  paziConsumer:
    image: paziconsumer:v1
    hostname: paziConsumer
    ports:
    - "11004:11004"
    depends_on:
      - paizEureka
      - paziGateway
      - paziProducer
    volumes:
      - "./entrypoint.sh:/entrypoint.sh"
    environment:
      SLEEP_SECOND: 4
    tty: true
    entrypoint: /entrypoint.sh -d paziProducer:11003 -c 'java -jar /app.jar';